### ISSUE TITLE
Hello, Friend

### ISSUE THREAD

**Issue by darrow-olykos** [jedahu/ts-refined#1]
So uh, you're a genius.

I haven't taken the time to deeply compare/contrast with this paper of yours I found ( https://goto.ucsd.edu/~pvekris/docs/pldi16.pdf ), but is this repo a demonstration of that research?

You uh, by chance interested in making this MIT Licensed?
Asking for a friend

**Comment by jedahu** [comment]
Hey, that paper isn't mine.

I have no problem making this MIT licensed, however I think you will be better off using a project that is maintained, like https://github.com/paarthenon/variant.
